name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: 'Whether to update the playwright reference screenshots'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  ci:
    runs-on: depot-ubuntu-24.04,dagger=0.19.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for changed apps detection
      - name: Run Pipeline
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: |
          dagger call ci \
          --source=. \
          --turbo-token=env:TURBO_TOKEN \
          --turbo-team="${{ vars.TURBO_TEAM }}" \
          --vercel-token=env:VERCEL_TOKEN \
          --bypass-secret=env:VERCEL_AUTOMATION_BYPASS_SECRET \
          --base="${{ github.event.before }}" \
          --update-snapshots=${{ inputs.update_snapshots || false }} \
          --is-prod=${{ github.ref_name == 'main' }} \
          --branch-name="${{ github.head_ref || github.ref_name }}" \
          --commit-sha="${{ github.sha }}"
